version: '3'
services:
  web:
    image: my-modx-image
    container_name: modx_web
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:10.1
    container_name: modx_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: modx
      MYSQL_USER: modx
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
  modx:
    image: my-modx-image
    build:
      context: .
      dockerfile: Dockerfile.modx
    working_dir: /var/www/html
